//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace airen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int ID { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Confirmpwd { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Profession { get; set; }
        public string Type { get; set; }
        public string IsOnline { get; set; }
    }
}
